services:
  app:
    build: ./
    container_name: assistant-app
    ports:
      - 8080:8080
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
  database:
    container_name: assistant-db
    image: postgres:latest
    volumes:
      - ./sandbox-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5434:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s